- name: Run Apt Update
  shell: apt update

- name: Install Nginx Server
  apt: >
    name=nginx
    state=present

- name: Copy the index.j2 Template to index destination folder
  template: >
    src=index.j2
    dest=/var/www/html/index.nginx-debian.html
    owner=root
    group=root
    mode=0644
  notify:
    - restart nginx

- name: Copy the style files to destination folder
  copy: >
    src=style.css
    dest=/var/www/html/style.css
    owner=root
    group=root
    mode=0644
  notify:
    - restart nginx

- name: Copy the javascript files to destination folder.
  copy: >
    src=scorekeeper.js
    dest=/var/www/html/scorekeeper.js
    owner=root
    group=root
    mode=0644
  notify:
    - restart nginx
